### ISSUE TITLE
How do I get the current index of the datapoint?

### ISSUE THREAD

**Issue by moneytree-doug** [gionkunz/chartist-js#416]
In D3, it always returns the index, and the datapoint. It provides a lot more meta information. For example, in a bar chart plotted against months and if I add an on-click handler to ``.ct-bars``, how would I get the current month for the bar clicked (which is the index of the datapoint in this case)?

**Comment by gionkunz** [comment]
Here's a simple example on how to use meta data and the Chartist serialization / deserialization capability. Meta data will be serialized and written onto the element attribute `ct:meta` from which it can be obtained later and deserialized with `Chartist.deserialize`.

The difference here is that you need to write your data using the object notation and must specify what you'd want to be your meta data. But this of course also gives you the freedom to do what ever you want. Value can be obtained by reading the `ct:value` attribute and convert to number.

Here's the example: http://jsbin.com/nokeza/edit?html,js,output

I've opened #421 to include a meta data example in the docs.

Hope this helps. Let me know if you find this weird to work with or if you like it.

Cheers
Gion

**Comment by moneytree-doug** [comment]
Perfect. Thank you!

**Comment by timwis** [comment]
Hi, just coming across this from researching. I'm trying to get the label of the bar that's been clicked. Can you confirm this is the only/best way to do that?
